const projects = [
  {
    id: 1,
    name: 'optica store',
    img: 'optica.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/optica/dist/',
    category: 'e-commerce',
    pageType: 'multi-page',
    year: '2026',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript', 'Vite'],
  },
  {
    id: 2,
    name: 'vue store',
    img: 'phones-vue.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://vue-store-eta.vercel.app/',
    category: 'e-commerce',
    pageType: 'landing',
    year: '2026',
    techStack: [
      'HTML',
      'CSS',
      'SCSS',
      'JavaScript',
      'Vue.js',
      'Tailwind',
      'Vite',
    ],
  },
  {
    id: 3,
    name: 'MK ai landing',
    img: 'ai-landing.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/MK-ai-landing/dist/',
    category: 'landing',
    pageType: 'multi-page',
    year: '2025',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript', 'Vite'],
  },
  {
    id: 4,
    name: 'photographer',
    img: 'portfolio-photo.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/photographer/dist/',
    category: 'landing',
    pageType: 'landing',
    year: '2025',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript', 'Vite'],
  },
  {
    id: 5,
    name: 'paris palase of culture',
    img: 'louvre.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/paris-palase-of-culture/dist/',
    category: 'landing',
    pageType: 'multi-page',
    year: '2025',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript', 'Vite'],
  },
  {
    id: 6,
    name: 'New Year Shop',
    img: 'new-york-store.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/New-Year-Shop/dist/',
    category: 'landing',
    pageType: 'multi-page',
    year: '2025',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript', 'Vite'],
  },
  {
    id: 7,
    name: 'coffee',
    img: 'coffee.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/coffee/dist/',
    category: 'e-commerce',
    pageType: 'multi-page',
    year: '2025',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript', 'Vite'],
  },
  {
    id: 8,
    name: 'store optica',
    img: 'store-optica.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/store-optica/dist/',
    category: 'e-commerce',
    pageType: 'landing',
    year: '2024',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript', 'Vite'],
  },
  {
    id: 9,
    name: 'Relvise',
    img: 'relvise.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/Relvise/dist/',
    category: 'landing',
    pageType: 'landing',
    year: '2025',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript', 'Vite'],
  },
  {
    id: 10,
    name: 'landing',
    img: 'landing.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/landing/dist/',
    category: 'landing',
    pageType: 'landing',
    year: '2025',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript', 'Vite'],
  },
  {
    id: 11,
    name: 'Funiro main',
    img: 'Funiro1.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/Funiro/Funiro-main/',
    category: 'landing',
    pageType: 'landing',
    year: '2024',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript', 'Gulp'],
  },
  {
    id: 12,
    name: 'rentiz',
    img: 'rentiz1.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/rentiz/',
    category: 'landing',
    pageType: 'landing',
    year: '2024',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript'],
  },
  {
    id: 13,
    name: 'alex Portfolio',
    img: 'alex1.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/alexPortfolio/dist/',
    category: 'landing',
    pageType: 'landing',
    year: '2024',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript', 'Gulp'],
  },
  {
    id: 14,
    name: 'roboSchool',
    img: 'roboschool.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/roboSchool/app/',
    category: 'landing',
    pageType: 'landing',
    year: '2024',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript', 'Gulp'],
  },
  {
    id: 15,
    name: 'fv',
    img: 'fr1.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/fv/',
    category: 'landing',
    pageType: 'landing',
    year: '2024',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript'],
  },
  {
    id: 16,
    name: 'home',
    img: 'home.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/home/',
    category: 'landing',
    pageType: 'landing',
    year: '2024',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript'],
  },
  {
    id: 17,
    name: 'pulse',
    img: 'pulse.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/pulse/src/',
    category: 'landing',
    pageType: 'landing',
    year: '2023',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript'],
  },
  {
    id: 18,
    name: 'grow',
    img: 'grow.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/grow/src/',
    category: 'landing',
    pageType: 'landing',
    year: '2023',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript'],
  },
  {
    id: 19,
    name: 'Real Estate',
    img: 'estate_1.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/RealEstate/src/',
    category: 'landing',
    pageType: 'landing',
    year: '2023',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript'],
  },
  {
    id: 20,
    name: 'lamborghini',
    img: 'lambo.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/lamborghini/dist/',
    category: 'landing',
    pageType: 'landing',
    year: '2023',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript'],
  },
  {
    id: 21,
    name: 'Recidiviz',
    img: 'Recidiviz.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/Recidiviz/dist/',
    category: 'landing',
    pageType: 'landing',
    year: '2023',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript'],
  },
  {
    id: 22,
    name: 'RGym',
    img: 'RGym.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/RGym/src/',
    category: 'landing',
    pageType: 'landing',
    year: '2023',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript'],
  },
  {
    id: 23,
    name: 'ujjo',
    img: 'ujio.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/ujjo2/',
    category: 'landing',
    pageType: 'landing',
    year: '2023',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript'],
  },
  {
    id: 24,
    name: 'store',
    img: 'Store.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/store/',
    category: 'landing',
    pageType: 'landing',
    year: '2023',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript'],
  },
  {
    id: 25,
    name: 'cab',
    img: 'cabins.png',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/cab/',
    category: 'landing',
    pageType: 'landing',
    year: '2023',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript'],
  },
  {
    id: 26,
    name: 'Fitness',
    img: 'fitness.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/Fitness/dist/',
    category: 'landing',
    pageType: 'landing',
    year: '2023',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript'],
  },
  {
    id: 27,
    name: 'lidia',
    img: 'lidia.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/lidia/',
    category: 'landing',
    pageType: 'landing',
    year: '2023',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript'],
  },
  {
    id: 28,
    name: 'uber',
    img: 'uber.webp',
    github: 'https://github.com/ivan-mr1/',
    deploy: 'https://ivan-mr1.github.io/uber/src/',
    category: 'landing',
    pageType: 'landing',
    year: '2023',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript', 'Bootstrap'],
  },
  {
    id: 29,
    name: 'react to do list',
    img: 'optica.webp',
    github: 'https://github.com/ivan-mr1/react-todo',
    deploy: 'https://ivan-mr1.github.io/react-todo/',
    category: 'to do list',
    pageType: 'multi-page',
    year: '2026',
    techStack: ['HTML', 'CSS', 'SCSS', 'React', 'CSS modules', 'Vite'],
  },
  {
    id: 30,
    name: 'react crypto',
    img: 'optica.webp',
    github: 'https://github.com/ivan-mr1/crypto-react',
    deploy: 'https://crypto-react-roan.vercel.app/',
    category: 'e-commerce',
    pageType: 'landing',
    year: '2026',
    techStack: ['HTML', 'React', 'Ant Design', 'Vite'],
  },
  {
    id: 31,
    name: 'vue weather',
    img: 'optica.webp',
    github: 'https://github.com/ivan-mr1/vue-weather',
    deploy: 'https://vue-weather-orcin.vercel.app/',
    category: 'weather',
    pageType: 'landing',
    year: '2026',
    techStack: ['HTML', 'Vue.js', 'Tailwind', 'Vite'],
  },
  {
    id: 32,
    name: 'to do list',
    img: 'optica.webp',
    github: 'https://github.com/ivan-mr1/To-Do-List',
    deploy: 'https://ivan-mr1.github.io/To-Do-List/dist/',
    category: 'to do list',
    pageType: 'landing',
    year: '2025',
    techStack: ['HTML', 'CSS', 'SCSS', 'JavaScript', 'Vite'],
  },
];

export default projects;
