import idGeneration from '../function/idGeneration';

const projects = [
  {
    name: 'MK-ai-landing',
    alt: 'MK Ai Landing',
    img: 'ai-landing.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/MK-ai-landing/dist/',
  },
  {
    name: 'photographer',
    alt: 'Photographer',
    img: 'portfolio-photo.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/photographer/dist/',
  },
  {
    name: 'paris-palase-of-culture',
    alt: 'Paris Palase Of Culture',
    img: 'louvre.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/paris-palase-of-culture/dist/',
  },
  {
    name: 'New-Year-Shop',
    alt: 'New Year Shop',
    img: 'new-york-store.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/New-Year-Shop/dist/',
  },
  {
    name: 'coffee',
    alt: 'Coffee',
    img: 'coffee.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/coffee/dist/',
  },
  {
    name: 'store-optica',
    alt: 'Store Optica',
    img: 'store-optica.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/store-optica/dist/',
  },
  {
    name: 'Relvise',
    alt: 'Relvise',
    img: 'relvise.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/Relvise/dist/',
  },
  {
    name: 'landing',
    alt: 'Landing',
    img: 'landing.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/landing/dist/',
  },
  {
    name: 'Funiro-main',
    alt: 'Funiro Main',
    img: 'Funiro1.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/Funiro/Funiro-main/',
  },
  {
    name: 'rentiz',
    alt: 'Rentiz',
    img: 'rentiz1.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/rentiz/',
  },
  {
    name: 'alexPortfolio',
    alt: 'Alex Portfolio',
    img: 'alex1.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/alexPortfolio/dist/',
  },
  {
    name: 'roboSchool',
    alt: 'Robo School',
    img: 'roboschool.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/roboSchool/app/',
  },
  {
    name: 'fv',
    alt: 'FV',
    img: 'fr1.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/fv/',
  },
  {
    name: 'home',
    alt: 'Home',
    img: 'home.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/home/',
  },
  {
    name: 'pulse',
    alt: 'Pulse',
    img: 'pulse.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/pulse/src/',
  },
  {
    name: 'grow',
    alt: 'Grow',
    img: 'grow.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/grow/src/',
  },
  {
    name: 'RealEstate',
    alt: 'Real Estate',
    img: 'estate_1.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/RealEstate/src/',
  },
  {
    name: 'lamborghini',
    alt: 'Lamborghini',
    img: 'lambo.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/lamborghini/dist/',
  },
  {
    name: 'Recidiviz',
    alt: 'Recidiviz',
    img: 'Recidiviz.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/Recidiviz/dist/',
  },
  {
    name: 'RGym',
    alt: 'RGym',
    img: 'RGym.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/RGym/src/',
  },
  {
    name: 'ujjo2',
    alt: 'Ujjo2',
    img: 'ujio.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/ujjo2/',
  },
  {
    name: 'store',
    alt: 'Store',
    img: 'Store.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/store/',
  },
  {
    name: 'cab',
    alt: 'Cab',
    img: 'cabins.png',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/cab/',
  },
  {
    name: 'Fitness',
    alt: 'Fitness',
    img: 'fitness.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/Fitness/dist/',
  },
  {
    name: 'lidia',
    alt: 'Lidia',
    img: 'lidia.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/lidia/',
  },
  {
    name: 'uber',
    alt: 'Uber',
    img: 'uber.webp',
    github: '',
    deploy: 'https://ivan1986mrpl.github.io/uber/src/',
  },
].map((project) => ({ id: idGeneration(), ...project }));

export default projects;
